# Generated by Django 5.0.6 on 2024-05-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='PersonModel',
        ),
    ]
